# yaml-language-server: $schema=https://json.schemastore.org/github-workflow
#
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: "Pull Request Labeler"
on:
  - pull_request_target

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read # for actions/labeler to determine modified files
      pull-requests: write # for actions/labeler to add labels to PRs
    runs-on: ubuntu-latest

    steps:
      # version between v4.0.3 and the one after which has not yet been tagged
      # at the time of writing
      - uses: actions/labeler@673e3c17b744f7cf2fd1b78ee9ed3e9e58c3a0c9
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: false
