name: Sign mixxx.msi

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: "Enter the id of the workflow run that has creates the unsigned exe"
        required: true
      signed_digest:
        description: "Enter signed digest, bas64 encoded"
        required: true

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Print Parameter Value
        run: |
          echo "The parameter value is ${{ github.event.inputs.parameter_name }}"
