name: Sign mixxx.exe

on:
  workflow_dispatch:
    inputs:
      workflow_run_id:
        description: "Enter the id of the workflow run that has creates the unsigned exe"
        required: true
      signed_digest:
        description: "Enter signed digest, bas64 encoded"
        required: true

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Print status
        run: |
          echo "Signing workflow ${{ github.event.inputs.workflow_run_id }} with"
          echo "${{ github.event.inputs.signed_digest }}"

      - name: "Download WIX project"
        uses: actions/download-artifact@v4
        with:
          name: WIX project
          run-id: ${{ github.event.inputs.workflow_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display structure of downloaded files
        run: ls

      - name: Sign mixxx.exe
        shell: powershell
        run: |
          $ProjectName = Get-ChildItem -Directory -Path D:\a\mixxx\mixxx\build\_CPack_Packages\win64\WIX  -Filter "mixxx-*" | Select-Object -First 1 -ExpandProperty Name
          Write-Host "ProjectName: $ProjectName"
          "${{ github.event.inputs.signed_digest }}" | Out-File -FilePath build\mixxx.exe.dig.signed -Encoding ASCII
          signtool sign /di build build\_CPack_Packages\win64\WIX\mixxx-*\Unspecified\mixxx.exe
          signtool timestamp /tr http://time.certum.pl /td sha256 build\_CPack_Packages\win64\WIX\mixxx-*\Unspecified\mixxx.exe
          SignTool verify /v build\_CPack_Packages\win64\WIX\mixxx-*\Unspecified\mixxx.exe
