name: Softfix workflow
on:
  issue_comment:
    types: [created]
jobs:
  softfix:
    name: Softfix action
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/softfix')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: daschuer/softfix@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
